name: RELEASE

on:
  push: 
    tags: 
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHA8: ${{github.sha}}
      REF: ${{ github.ref }}
    steps:
    - name: Echo env
      id: env
      run: env
      
    - name: Checkout
      id: checkout
      uses: actions/checkout@v2

    - name: Clean if use same agent
      id: clean
      run: ./gradlew clean

    - name: Build
      id: build
      run: ./gradlew build
      
    - name: Zip Package
      id: zip-package
      run: cd ./build/launch4j ; zip -r ../../Yuumi.zip *

    - name: Zip Jars
      id: zip-jars
      run: cd ./build/libs ; zip -r ../../Yuumi-jars.zip *

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Last build ${{ github.ref }}
        body: Last build branch[${{ github.ref }}] Sha[${{ github.sha }}]
        draft: false
        prerelease: true
        
    - name: Upload Release Zip
      id: upload-release-zip 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./Yuumi.zip
        asset_name: Yuumi.zip
        asset_content_type: application/zip
        
    - name: Upload Release Jar
      id: upload-release-jar
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./Yuumi-jars.zip
        asset_name: Yuumi-jars.zip
        asset_content_type: application/zip
